apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: myappns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
  spec:
    containers:
      - name: nginx
        image: akreng/devopsrepo:latest
        imagePullPolicy: Always  # Ensure the image is always pulled
        ports:
        - containerPort: 80
        imagePullSecrets:
      - name: docker-secret
